### ISSUE TITLE
HexaPDF via Sidekiq Segmentation Fault

### ISSUE THREAD

**Issue by Phillita** [gettalong/hexapdf#20] opened 2017-11-07 18:55 UTC
Hello,

I was hoping you might be able to provide me with a little help. I've run into a segmentation fault while using you gem on both versions 0.5.0 and 0.6.0. I've attached 2 different segfaults. 

I was able to run my job manually in a rails console without any issues. 
I'm using the latest version of sidekiq (5.0.5). 
The task being performed is taking a pdf and stamping another pdf onto it (one that is blank but has a header/footer banner).
I'm unsure if this is a sidekiq issue or if it's an issue with HexaPDF.

Any suggestions you have would be great!

[hexapdf_segfault1.txt](https://github.com/gettalong/hexapdf/files/1451244/hexapdf_segfault1.txt)
[hexapdf_segfault2.txt](https://github.com/gettalong/hexapdf/files/1451245/hexapdf_segfault2.txt)

If you need more information, I'd be glad to try to get that for you.

**Comment by gettalong** [comment] 2017-11-08 18:36
HexaPDF relies on fibers for processing stream data and the traces you sent seem to indicate that the segfault happens when the PDF gets written. This is also the time where, potentially many, fibers are created for writing the streams to the output IO.

What I found during development was that when using HexaPDF in conjunction with a certain C extension (I don't remember which one, probably `allocation_tracer` or `ruby-prof`) segfaults *sometimes* happened; but not always. So this may also be the reason in your case, i.e. a problematic C extension.

It may also be due to the way sidekiq uses threads but I'm no expert in this regard. The reason is that Fiber and Thread are somewhat interrelated in that each Thread has at least one Fiber, the root fiber.

You may also try to reduce the number of loaded gems to see which one leads to the segfault. Then it may be possible to provide a reproducible bug report to the Ruby core team to see whether a bug in Ruby itself is triggered.

Alas, I don't use sidekiq or most of the other gems in your trace so I can't tell you whether one or the other relies on native extensions or heavy thread usage.

**Comment by gettalong** [comment] 2017-12-25 11:33
@Phillita I'm closing this issue for now but if you have any leads on which interaction is causing the segfault or if you have a reproducible test case that you can share, feel free to add a comment and I will reopen the issue.

**Closed by gettalong** 2017-12-25 11:33 UTC

**Comment by jalevin** [comment] 2018-09-03 19:33
I've got a follow up to this. When running bates_stamper.rb one off or in a loop, I don't have any issues. 

The error that that's actually being thrown with the malformed pdf, should be caught by sidekiq and requeued.
 
[sidekiq_hexa_segfault.txt](https://github.com/gettalong/hexapdf/files/2346454/sidekiq_hexa_segfault.txt)

**Comment by gettalong** [comment] 2018-09-04 03:47
@jalevin Please try the latest version 0.7.0 of HexaPDF which has a fix for this. See https://hexapdf.gettalong.org/documentation/changelog.html
