### ISSUE TITLE
Required field BBox is not set

### ISSUE THREAD

**Issue by zeninfinity** [gettalong/hexapdf#58] opened 2019-02-11 23:17 UTC
Hello,

Testing out this gem and got the following error:

```
.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:618:in "block in write": Validation error for (3029,0): Required field BBox is not set (HexaPDF::Error)
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:569:in "block in validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/object.rb:269:in "block (2 levels) in validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:269:in "block in perform_validation"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:254:in "block in each_set_key_or_required_field"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:121:in "each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:121:in "each_field"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:253:in "each_set_key_or_required_field"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/dictionary.rb:261:in "perform_validation"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/stream.rb:282:in "perform_validation"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/object.rb:268:in "block in validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/object.rb:267:in "catch"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/object.rb:267:in "validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:574:in "block in validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:403:in "block (2 levels) in each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/revision.rb:185:in "block in each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/utils/object_hash.rb:117:in "block in each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/utils/object_hash.rb:117:in "each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/utils/object_hash.rb:117:in "each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/revision.rb:183:in "each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:401:in "block in each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:400:in "reverse_each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:400:in "each"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:572:in "validate"
        from /.rvm/gems/ruby-2.4.0/gems/hexapdf-0.9.0/lib/hexapdf/document.rb:616:in "write"
        from modify-pdf2.rb:3:in "<main>"
```

I broke the file down to virtually nothing:

```
require 'hexapdf'
doc = HexaPDF::Document.open('sourcefile.pdf')
doc.write('oh-yea-i-exist.pdf', optimize: true)
```

And I still get this issue above.  Not sure exactly how to proceed?

**Comment by zeninfinity** [comment] 2019-02-11 23:36
Looks like I can write with the following to get it to work:
```
doc.write('oh-yea-i-exist.pdf', optimize: true, validate: false)
```

Are there reasons why validation didn't work with what I believe to be a known-good pdf?  Can you explain the BBox error a bit to me?

Thanks.

ZZ

**Comment by gettalong** [comment] 2019-02-12 21:53
It may be a problem with your PDF or it may be a bug in the validation feature. If you can send me the PDF, I can have a look at it and determine which of these two options it is.

As for BBox: A PDF file consists of a series of PDF objects (not completely accurate but okay for this explanation). Many of these PDF objects are so called "dictionaries", lists of key-value pairs (think `Hash` in Ruby), and the available keys for each object are described in the PDF specification. HexaPDF represents such PDF dictionaries as objects of type `HexaPDF::Dictionary`. Since we know the available keys, their allowed values and whether a key is required or not, we can use this information for validation by creating special classes which know about the keys (note that HexaPDF does not have special implementation for all PDF dictionaries, yet).

The BBox key itself is used by form XObjects which are like PDF pages in the sense that they can contain any drawing operations but can be used like images (i.e. multiple times on a single page or on multiple pages).

**Comment by gettalong** [comment] 2019-06-13 14:09
@zeninfinity Can you provide the/a faulty PDF for inspection?

**Comment by gettalong** [comment] 2019-07-23 20:45
@zeninfinity  I will close this issue because you didn't provide the faulty PDF for inspection and without it I cannot proceed further. Feel free to post more information on the issue and I will re-open it.

**Comment by iamjohnford** [comment] 2019-09-09 16:48
I also ran into the same issue while testing HexaPDF.

**Test file**

https://www.uscis.gov/sites/default/files/files/form/g-325a.pdf

**Code**
```ruby
require 'hexapdf'
doc = HexaPDF::Document.open('g-325a.pdf')
doc.write('output.pdf')
```

**Stacktrace**
```
Traceback (most recent call last):
       16: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:188:in `block in each'
       15: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:406:in `block (2 levels) in each'
       14: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:577:in `block in validate'
       13: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/object.rb:270:in `validate'
       12: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/object.rb:270:in `catch'
       11: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/object.rb:271:in `block in validate'
       10: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/stream.rb:285:in `perform_validation'
        9: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:264:in `perform_validation'
        8: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:256:in `each_set_key_or_required_field'
        7: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:124:in `each_field'
        6: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:124:in `each'
        5: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:257:in `block in each_set_key_or_required_field'
        4: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:272:in `block in perform_validation'
        3: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/object.rb:272:in `block (2 levels) in validate'
        2: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:572:in `block in validate'
        1: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:621:in `block in write'
HexaPDF::Error (Validation error for (54,0): Required field BBox is not set)
```

I don't know if there are quirks with encrypted PDFs but when trying `validate: false` a different error occurs.

**Code**
```ruby
require 'hexapdf'
doc = HexaPDF::Document.open('g-325a.pdf')
doc.write('output.pdf', validate: false)
```

**Stacktrace**

```
Traceback (most recent call last):
       16: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/writer.rb:112:in `write_revision'
       15: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/writer.rb:165:in `xref_and_object_streams'
       14: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:186:in `each'
       13: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `each'
       12: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `each'
       11: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/utils/object_hash.rb:120:in `block in each'
       10: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:188:in `block in each'
        9: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/revision.rb:225:in `load_object'
        8: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:214:in `block (2 levels) in set_up_decryption'
        7: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:259:in `decrypt'
        6: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:513:in `each_string_in_object'
        5: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:513:in `each_value'
        4: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:513:in `block in each_string_in_object'
        3: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:517:in `each_string_in_object'
        2: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/security_handler.rb:261:in `block in decrypt'
        1: from /ruby-2.6.3/gems/hexapdf-0.9.3/lib/hexapdf/encryption/aes.rb:118:in `decrypt'
HexaPDF::EncryptionError (Invalid data for decryption, need 32 + 16*n bytes)
```

**Comment by gettalong** [comment] 2019-09-09 21:03
@iamjohnford Thanks for providing the PDF. I was able to reproduce both problems.

I now know the reason for BBox problem (a so called structure element has `/Subtype /Form`) and why it happens (HexaPDF maps the dictionary to `HexaPDF::Type::Form` although it isn't one). Will have to see how such cases should be handled.

As for the decryption problem: Will have to look into that!

**Comment by gettalong** [comment] 2019-09-09 22:12
As for the decryption problem: It seems that there are additional objects that must not be encrypted because they are added later. In this case this seems to be the case for a digital signature hash.

**Comment by iamjohnford** [comment] 2019-09-11 02:16
I don't know if it's helpful, but here are a few more test documents that seem to be giving the same error.

https://www.irs.gov/pub/irs-pdf/f941.pdf
https://www.irs.gov/pub/irs-pdf/fw4.pdf
https://www.irs.gov/pub/irs-pdf/fw9.pdf

None of these are encrypted so `validate: false` seems to work okay but cannot be optimized because of errors like `HexaPDF::MalformedPDFError (Object with oid=53 is not an object stream)`. I'm guessing that's related to the dictionary mapping not being correct?

**Comment by gettalong** [comment] 2019-09-16 08:00
@iamjohnford Could you test with the latest repository version? All bugs should be fixed, at least I don't get any more problems with the test files you provided.

@zeninfinity Could you also test again?

**Comment by iamjohnford** [comment] 2019-09-16 22:42
@gettalong Works for me! Thanks!

**Comment by gettalong** [comment] 2019-09-17 19:55
@iamjohnford Thanks for testing! Will release the new version sometime this week!

**Closed by gettalong** 2019-09-17 19:55 UTC
