### ISSUE TITLE
Number-formatting of text-field gets lost when flattening acro_form

### ISSUE THREAD

**Issue by andi-dev** [gettalong/hexapdf#220] opened 2022-12-12 12:05 UTC
Hi again,

In a pdf containing a text field with number formatting, when flattening the form the formatting seems to be lost.

Original pdf:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/152931/207040583-31bd4868-665d-42f6-b3a9-5f255c28593a.png">

Resulting pdf:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/152931/207040607-fa077aad-a153-4667-8565-e8641223306c.png">

Screenshot from Acrobat:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/152931/207040467-6916771c-cf05-41af-9438-103a0003dab7.png">

I did not yet have time to look into the code and see how feasible it even is to persist the formatting when re-creating the fields appearance, but maybe that is something you already thought about?

Cheers!

ps: let me know if the original pdf would be helpful.

**Comment by gettalong** [comment] 2022-12-12 22:46
It would be great, if you could send me the PDF because then I can determine whether this is some kind of Javascript code doing the formatting or something else.  Thanks!

**Comment by gettalong** [comment] 2022-12-17 12:01
@andi-dev I did some digging and only found solutions that involve Javascript. If you could provide the PDF, I could verify that this is also the case in your situation.

FYI: HexaPDF doesn't include a Javascript engine, so if this is Javascript based, it won't work.

**Comment by andi-dev** [comment] 2022-12-17 13:36
Hi Thomas, sorry for the late reply. I just sent you the pdf.

**Comment by gettalong** [comment] 2022-12-17 15:37
Thanks Andreas! I can confirm that this the PDF is also using Javascript to format the numbers. It seems that Adobe defined a Javascript method `AFNumber_Format` which is used in all the cases I have looked at so far. I will see if I can find a reference documentation for that method. It may be possible to just parse the Javascript method arguments and synthesize the needed result.

**Comment by gettalong** [comment] 2022-12-18 15:51
Okay, I found https://experienceleague.adobe.com/docs/experience-manager-learn/assets/FormsAPIReference.pdf?lang=en but it doesn't seem to accurately reflect things as `sepStyle` is 2 in the PDF you provided and that is not listed there.

However, I *think* I can come up with something to make this work even without proper Javascript support, provided the PDF file follows the same scheme that I have now seen multiple times.

**Comment by gettalong** [comment] 2022-12-18 23:25
@andi-dev I now have a draft implementation of the `AFNumber_Format` method and it works, at least for your supplied PDF (the third number was filled-in and rendered by HexaPDF):

![image](https://user-images.githubusercontent.com/4104/208324672-df6c55f7-1ffa-4917-a53f-8c682e454329.png)

What you might also have noticed on the above screenshot is that the rendered form field uses the correct font! I saw that the font used for the form field was fully embedded and not a subset and enhanced HexaPDF to use this font. This won't work in all cases but it should provide a better out-of-the-box experience for many more PDFs with interactive forms.

**Comment by gettalong** [comment] 2022-12-26 22:17
Will be in the upcoming release.

**Closed by gettalong** 2022-12-26 22:17 UTC
Labels: enhancement
