### ISSUE TITLE
Issue with utf-8 character in filled form field after flattening acro_form

### ISSUE THREAD

**Issue by andi-dev** [gettalong/hexapdf#203] opened 2022-10-27 19:30 UTC
Hi there! 

I am evaluating hexapdf for a customer project, and I ran into an isuse while trying to flatten an included acro_form in order to make the pdf "read only". The characters simply disappear after modifying it with hexapdf. 

Before: 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/152931/198380376-2385ec43-5b2a-42b0-b6b1-b3a920d6183a.png">

After:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/152931/198380407-310bf16a-bf49-4b67-9181-07c8eda48558.png">

Steps to reproduce:

1. I downloaded an example pdf created with openoffice from here: http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf
2. I opened it with Preview on my Mac (12.4) filled the first to form fields with "Pöter" and "Pän".
3. I modified the pdf with hexapdf and the following code:

```
in_doc = HexaPDF::Document.open("OoPdfFormExample.pdf")
in_doc.acro_form.flatten
in_doc .catalog.delete(:AcroForm)
in_doc.delete(in_doc.acro_form)
out_doc = HexaPDF::Document.new
out_doc.pages << out_doc.import(in_doc.pages.first)
out_doc.write("out.pdf")
```

It is worth noting, that the issue only manifests with the combination of a) flattening the acroForm and b) importing the page into a new document.

Do you have any idea what could have happened?

Btw. with another test-document I noticed that only some of the form fields have been "deactivated" by `acro_form.flatten`, and quite a few have been returned as they could not be removed. Looking into the code, it seems that fields with a "Widget" associated can not be removed., but I fail to understand why - and if there are any suggestions on how to proceed with those.

Thank you a lot :)

**Comment by gettalong** [comment] 2022-10-27 20:38
So what happens is that with `in_doc.acro_form.flatten` HexaPDF tries to create the appearances of the form fields. Text fields are always regenerated because of the difficulty to determine whether an associated appearance stream actually contains the fields value. Since the form uses a font that HexaPDF currently can't use for creating the fields' appearances, it falls back to the configuration option `acro_form.fallback_font` and uses the Helvetica font. The created font object, however, is only completed when writing the file out (because HexaPDF doesn't know when and where the font is used, it stores all used characters and on writing creates the correct PDF font objects for the used characters; otherwise it would need to build the font object on every changed to the used characters).

When you import the page, all resources including the used fonts are copied but the font objects are not yet completed and missing some information to correctly use them. This leads to the umlauts not appearing although they are actually specified in the content streams.

You can work around this in two ways:

* Use `in_doc.acro_form.flatten(create_appearances: false)` to make HexaPDF use the existing appearances. This should mostly be fine. However, some PDF libraries only change the form field values without creating the appropriate appearance streams, delegating this work to the viewer. In such a case nothing would appear in the flattened page.

* Manually specify that HexaPDF should complete all objects by calling `in_doc.dispatch_message(:complete_objects)`. After this the font objects are completed.

---

As for your second question: There is an error in the documentation for `Form#flatten` as it states that the returned array contains form fields while it contains form field widgets. Those returned widgets don't have an associated appearance stream and could therefore not be flattened (a form field is just a PDF object, it can have one or more widget annotations associated with it that define its appearance).

If you just want to flatten the form and not specially handle those returned widgets, you could use:

~~~
in_doc.acro_form.flatten.each {|widget| widget.form_field.delete_widget(widget)}
~~~

**Comment by andi-dev** [comment] 2022-10-28 08:40
Wow, thank you for the quick response! 🙂 

I tried out ´in_doc.dispatch_message(:complete_objects)`, as having fields missing entirely in the flattened page doesn't sound like the best option. It works and solves the umlaut-issue. Thank you!

Regarding the second question: Manually deleting the widgets seems to work, and all "normal" fields are disabled. (checkboxes however can still be checked)

With the following script:

````
in_doc = HexaPDF::Document.open("../../../Downloads/Rechnungsbegleitblatt.pdf")
in_doc.acro_form.flatten#.each {|widget| widget.form_field.delete_widget(widget)}
in_doc.catalog.delete(:AcroForm)
in_doc.delete(in_doc.acro_form)
in_doc.dispatch_message(:complete_objects)
in_doc.write("out1.pdf")
out_doc = HexaPDF::Document.new
out_doc.pages << out_doc.import(in_doc.pages.first)
out_doc.write("out.pdf")
```

out1.pdf is saved just fine, but the import fails with an error:

```
out_doc.pages << out_doc.import(in_doc.pages.first)
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/dictionary.rb:201:in `key?'
```

it looks like something got messed up when trying to flatten the form. From what I understand there might always be the "odd" pdf that is hard to handle, and it would be fine if flattening forms doesn't always work perfectly. But it would be nice if I had some path to fall back and give up the attempt to flatten the form.

Let me know if I can provide more helpful details. I am not sure if I can share the pdf, but if it would help I will inquire.

Thank you :)

**Comment by gettalong** [comment] 2022-10-28 20:57
> Regarding the second question: Manually deleting the widgets seems to work, and all "normal" fields are disabled. (checkboxes however can still be checked).

You need to additionally delete the main acroform object like with your initial code:

~~~
in_doc.delete(in_doc.acro_form)
~~~

However, this only makes sense if you write `in_doc` as the `out_doc` won't have the acroform object anyway.

---

If you write out a file, you won't need to dispatch the :complete_objects message as this is done by the `#write` method.

The `NoMethodError` would indicate that an object was deleted and then later accessed. Could you provide the full HexaPDF related stacktrace?

**Comment by andi-dev** [comment] 2022-10-29 20:25
Hi Thomas,

thanks again for your reply! I digged a bit deeper, and from what I understand `in_doc.acro_form.flatten` leaves a reference to a `Kid` which is `nil`. Then I get the error either when deleting widgets with `in_doc.acro_form.flatten.each {|widget| widget.form_field.delete_widget(widget)}`...

```
#<NoMethodError: undefined method `key?' for nil:NilClass>
(byebug) pp e.backtrace
["/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/type/acro_form/field.rb:236:in `block in terminal_field?'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/pdf_array.rb:183:in `block in each'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/pdf_array.rb:183:in `each_index'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/pdf_array.rb:183:in `each'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/type/acro_form/field.rb:236:in `none?'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/type/acro_form/field.rb:236:in `terminal_field?'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/type/annotations/widget.rb:94:in `form_field'",
```

or, when I skip removing the widgets (-> simply calling `in_doc.acro_form.flatten`) I run into this error when importing the page into `out_doc`.

```
(byebug) pp e.backtrace
["/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/dictionary.rb:201:in `key?'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/dictionary.rb:166:in `[]'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/dictionary.rb:226:in `type'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:118:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `block in duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `map'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:132:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `block in duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `transform_values'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:132:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `block in duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `transform_values'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:132:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `block in duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `map'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:114:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:132:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `block in duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `transform_values'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:112:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:132:in `duplicate'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/importer.rb:99:in `import'",
 "/Users/buddhabox/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hexapdf-0.26.2/lib/hexapdf/document.rb:266:in `import'",
```

I added a debugger to `HexaPDF::Type::AcroForm::Field#terminal_field?`, and indeed I found at least one `PdfArray` with a `nil`-value.  When I locally changed this line https://github.com/gettalong/hexapdf/blob/REL_0_26_2/lib/hexapdf/type/acro_form/field.rb#L236 to `kids.nil? || kids.empty? || kids.none? {|kid| kid && kid.key?(:T) }` the code works...

**Comment by gettalong** [comment] 2022-10-29 20:43
Thanks for providing the stack traces and the additional information!

I'm still not quite sure how this happens because in `#flatten` the field should be deleted from its parent's /Kids array:

~~~
          fields.each do |field|
            (field[:Parent]&.[](:Kids) || self[:Fields]).delete(field)
            document.delete(field)
          end
~~~

The first reason I can think of why this happens is if the /Parent entry is missing.

Could you run `hexapdf inspect INPUT.PDF r` and provide the output? That would help me determine whether the PDF object structure is correct.

The changed line will definitely help with this scenario but may fail in others. So if HexaPDF is the reason for the exception I want to fix it at the source.
It would be even better if you could share the PDF (under an NDA if needed) so that I can have a look at it. Contact me at info@gettalong.at if that would work for you.

**Comment by andi-dev** [comment] 2022-10-30 09:19
I am starting to suspect that the original pdf is in some way broken. When I use the `pdfinfo` command line tool, I get two warnings which seem to be related to the issue. I will send you this particular pdf via email. Thank you for taking the time to look into this!

```
Creator:         Acrobat PDFMaker 20 für Excel
Producer:        macOS Version 12.1 (Build 21C52) Quartz PDFContext, AppendMode 1.1
CreationDate:    Thu Feb 24 09:36:20 2022 CET
ModDate:         Wed Oct 26 10:14:09 2022 CEST
Custom Metadata: yes
Metadata Stream: yes
Tagged:          yes
UserProperties:  no
Suspects:        no
Form:            AcroForm
Syntax Warning: SubType on non-terminal field, invalid document?
Syntax Warning: Field can't have both Widget AND Field as kids<0a>
JavaScript:      yes
Pages:           1
Encrypted:       no
Page size:       595.2 x 841.68 pts (A4)
Page rot:        0
File size:       1082119 bytes
Optimized:       no
PDF version:     1.6
```

**Comment by gettalong** [comment] 2022-10-30 10:39
Thanks - I will have a look at the file later today!

**Comment by gettalong** [comment] 2022-10-30 17:41
So, thanks again for providing the file.

I looked at the fields and how they are defined. Nearly all of the fields are in a flat hierarchy, i.e. directly referenced in the root fields array. However, there are two entries which are kids of another one. Those kids should have a /Parent entry referencing their parent. One of them does but the other doesn't. This is the reason of the syntax warning of `pdfinfo`.

If you run

~~~
in_doc.object(1088)[:Parent] = in_doc.object(21)
~~~

the field hierarchy is corrected and afterwards everything works.

My guess is that this is an error on behalf of the library/application that generated the file because the field's full name should be 'c_01_kk_kostenstelle.0.0` (the dots are hierarchy separators) but is actually `c_01_kk_kostenstelle.0.c_01_kk_kostenstelle.0.0` because the intended full name of the field is already its partial name.

The cause of the error is that the field itself is deleted, i.e. its value set to +nil+, but its reference from the parent's array is not since it is not correctly included in the hierarchy. So when the /Kids array of the parents is iterated, there is a reference to an item with a +nil+ value, leading to the error.

The other error, when importing the page into `out_doc`, has the cause: The field has a +nil+ value although it is wrapped by a dictionary class. This is usually not a problem but here it is due to the initial invalid object structure.

I will think about a way to remedy the problem. It is a bit more complicated since field iteration happens in a lot of places and fixing it in all places is error prone and... ugly.

**Comment by gettalong** [comment] 2022-11-04 21:52
@andi-dev So I will fix this by adding code to the validation routine of the main AcroForm object `doc.acro_form`. To ensure that you have a valid file (or auto-correct invalid object if possible) you would then need to call either `doc.acro_form.validate` for just this type of validation or `doc.validate` to validate the whole document.

I have thought about a few other ways to solve this but none of them are better and they would degrade the HexaPDF user experience.

**Comment by andi-dev** [comment] 2022-11-07 12:04
@gettalong if I have a chance to validate if the pdf has a valid form structure before attempting to flatten it, this should be fine. If some issues can be auto-corrected even better :)

Looking forward to trying out the updated version of hexapdf - thank you for your support so far!

**Comment by gettalong** [comment] 2022-11-15 21:29
@andi-dev I have implemented the needed changes and your test case now works if you validate the AcroForm field tree before doing anything with it. You can try it out using the [actions branch](https://github.com/gettalong/hexapdf/tree/actions). 

The next version with the change will be released in a few days.

**Closed by gettalong** 2022-11-15 21:29 UTC
