### ISSUE TITLE
HexaPDF::Error (Validation error: Type of field D is invalid: String)

### ISSUE THREAD

**Issue by Phill** [gettalong/hexapdf#42] opened 2018-08-13 19:04 UTC
I get this with a lot of PDF's that I'm testing with. Not sure what it means.

HexaPDF::Error (Validation error: Type of field D is invalid: String)

Thanks

**Comment by gettalong** [comment] 2018-08-13 19:57
These are probably documents using actions (like clicking on a link and going to a specific page or opening an URL) because those have a D field.

I *think* I found the problem but will have to add a full test case to verify and will get back to you then - thanks for reporting!

**Comment by Phill** [comment] 2018-08-13 20:02
I just checked and these PDF's I have do have links in them.

**Comment by gettalong** [comment] 2018-08-13 20:11
Thanks for checking and confirming!

**Comment by gettalong** [comment] 2018-08-18 05:35
The problem is that some PDF fields can have multiple different types of data, e.g. the value can be a string OR an array OR a hash. And the validation currently only kicks in correctly if the field has a single type. In most cases with multiple types it is still okay but not in all.

I will have to rethink (and probably redo) the field validation feature for this to work better and more correct.

**Comment by gettalong** [comment] 2018-09-08 09:39
@Phill I have implemented a fix for this problem and tested it on a document with a GoToR action that uses a string for the D field. Will be in the next release.

**Closed by gettalong** 2018-09-08 09:39 UTC
Labels: bug
