### ISSUE TITLE
Multiple Signature example resulting in Invalid Byte Range

### ISSUE THREAD

**Issue by jotolo** [gettalong/hexapdf#202] opened 2022-10-21 16:02 UTC
Hi @gettalong , our team is trying to integrate hexapdf to our signature tool.
We tried the example code provided in the docs for [multiple signatures](https://hexapdf.gettalong.org/documentation/howtos/signing-pdfs.html#multiple) and the result is giving us an invalid byte range with any PDF we tried.
We used Acrobat Reader and [PDF Studio Viewer](https://www.qoppa.com/pdfstudio/download/) to test results.
The following image is from PDF Studio Viewer checking the result of the example code mentioned before for multiple signature.

![CleanShot 2022-10-21 at 17 41 37](https://user-images.githubusercontent.com/6193238/197238907-1f4deafd-3dca-4ac2-a445-acd726415d79.png)

For some reason is having an issue with Invalid Byte Range for all the signatures except the last one.
Any help will be very much appreciated. 

HexaPDF v0.26.1

Thank you very much for hexapdf!

**Comment by gettalong** [comment] 2022-10-21 19:24
Thanks - I can reproduce the problem and have identified the cause.

**Comment by gettalong** [comment] 2022-10-21 19:41
The root cause is a change in how PDF objects are compared. This change, introduced in August this year, was meant to prevent output of invalid PDFs. However, a hitherto unknown side-effect was that existing signatures were deemed to have changed when writing a new revision (e.g. for another signature). This in itself would probably also not be a problem since the signature value stayed the same but it *was serialized differently* (the default method of serializing strings in HexaPDF is not the one that needs to be done for signature values). And this is probably what triggered the errors for Adobe Reader.

I will introduce two different fixes for this problem, one for the root cause and one specially for signatures and will release a bug fix version later today.

**Comment by gettalong** [comment] 2022-10-21 22:21
I just released 0.26.2 with a fix for this problem.

**Closed** 2022-10-22 06:43 UTC
Labels: bug

**Comment by jotolo** [comment] 2022-10-22 08:36
Thanks @gettalong for the quick fix. Very nice work with hexapdf 🖖
