### ISSUE TITLE
Adding images to PDFs in sidekiq causes memory build up

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#97] opened 2019-12-28 07:01 UTC
We've spent a lot of time trying to narrow down the cause of memory bloat issue and found that for some reason whenever we use HexaPDF to add small images ( under 100K) to PDFs in a job (using sidekiq) there's a large bump in memory usage each time. 

To fix this problem, all we have to do is comment out the single line that's adding images and memory usage goes way down. We're adding images in different ways and it results in the same problem.

Example: 
```
overlay = page.canvas(:type => :overlay)
overlay.image StringIO.new(element.to_png),
      at: [x, y],
      width: height * aspect_ratio,
      height: height
```
Example 2: 
```
output_pdf = HexaPDF::Composer.new(page_size: :Letter, margin: [pixel_to_point(52), pixel_to_point(107)]) do |pdf|
  pdf.image(activity_images[activity[:type]], width:pixel_to_point(21),
end
```

We tried iterating over all of the document images and deleting them and that didn't help. Tried `clear_cache` and `output_pdf = nil`. No luck. 

We're using Scout app to profile our app and it's showing a huge number of allocations that instantly go away if we don't add images to PDF (while still adding text and merging PDFs): https://share.getcloudapp.com/WnuEYNP2

(Note: it says 23% in there, but that's actually just part of the 25% because we're profiling the same method several ways...so it's basically almost 100% of the memory allocation that's being shown). 

Any thoughts on why the huge number of allocations and memory usage is happening with images? 

Here's an example of one of the images: https://share.getcloudapp.com/P8uY5RP8

**Comment by gettalong** [comment] 2019-12-28 13:50
I use the following test script:

~~~
require 'hexapdf'

HexaPDF::Composer.new(page_size: :Letter, margin: [100, 100]) do |pdf|
  pdf.image('gh97.png') # your provided image
  pdf.write('/tmp/gh97.pdf')
end
~~~

Using the `memory_profiler` gem shows about 66000 allocations by HexaPDF, nearly all for Type1 font support. So this doesn't really narrow it down.

One reason why the images might blow up memory usage is if they have an alpha channel, i.e. transparency interleaved with the image data. Because in this case HexaPDF has to parse the image data to separate the image itself and the transparency information.

How many images are you adding in one go?

**Comment by earthlingworks** [comment] 2019-12-28 21:04
Just about 5 to 8 images...all in the 2kB to 15KB size range. All but 4 of them are dynamically generated, and the dynamic ones do need to have transparency. 

I just ran the same test you did and you're right, I got 66,000 allocations by HexaPDF. But then I ran the same test referencing another image we're using (3KB)...nothing else changed (except for the image), and it has 21,700 allocations by HexaPDF. Also reported to be related to font support mostly. That's strange. I wouldn't think that a different image would change the number of allocations of font related objects by tens of thousands.

Here's the other image I used: https://share.getcloudapp.com/v1umbxOz

**Comment by earthlingworks** [comment] 2019-12-28 21:19
I just grabbed one of the dynamically generated images and tried it with that (same exact test code you have), and the numbers blew up: https://share.getcloudapp.com/p9u5bwZE

Image loader followed by the font support stuff. Almost 7 million allocations with that single image.

Here's the image I used: https://share.getcloudapp.com/RBuXYWJv

**Comment by gettalong** [comment] 2019-12-28 21:32
So, after a bit of further investigation it seems that PNG images with alpha channel might cause that problem.

When changing your provided image from the indexed color space to the RGBA (RGB with alpha channel) color space, [line 369 of the PNG image loader file](https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/image_loader/png.rb#L369) file appears to allocate many objects.

The line in question is `data[0, bytes_per_row] = ''`, ie, the front of the string `data` is removed. Since we are using frozen string literals, the empty string is only allocated once. However, it might be the case that the `[]=` method internally duplicates the string. If we change that line to `data = data[bytes_per_row..-1]`, allocations and retained objects drop. I also don't know why some objects are retained with the current code since we are just deleting part of a string....

**Comment by earthlingworks** [comment] 2019-12-28 21:44
Huh, that's interesting. Unfortunately, the images we're adding to PDFs have to have transparent backgrounds. I think we can do some minor optimizations on those images now that I'm looking at it, but it won't save us much.

**Comment by gettalong** [comment] 2019-12-28 22:12
Using your image from https://github.com/gettalong/hexapdf/issues/97#issuecomment-569451010 yields 66000 allocations for me.

As for the other image: This one is one with an alpha channel which has to be separated. The way this is stored in PNG is "RGBARGBARGBA..." for each line of pixels and we need to extract "RGB A RGB A RGB A...", so we need to slice the string into many pieces, yielding two allocations per pixel.

I just tried adding byte by byte using `String#getbyte` instead of all image/mask pixel data at once and it seems that this does not only reduce the allocations but is also about 3x faster for your test image. I will have a more thorough look at this later but if it works I will release a new version.

However, I still don't know why line 369 retains some memory. The better allocation behaviour of the new version probably stems from an internal MRI optimization where using the end of the string (`x..-1`) is optimized to not create a new string.

**Comment by earthlingworks** [comment] 2019-12-28 22:17
That would be great! Hope it works out for a new release.

Also, appreciate how amazingly responsive you've been with the couple of things I've submitted. Totally not expected going forward (as I know things come up and we all get busy), but just wanted to mention it because it's reinforcing the importance of being responsive with our own products.

**Comment by earthlingworks** [comment] 2019-12-28 22:22
And you're right about the 66k allocations on the logo image...I was looking at the wrong place before. Sorry about that!

**Comment by gettalong** [comment] 2019-12-28 22:55
I have just released version 0.11.4 - can you try it out? Would be interesting to see a memory consumption and performance comparison between the old and new versions!

**Comment by earthlingworks** [comment] 2019-12-29 02:10
Just tried it out and while it's tough to do a direct comparison of before/after, there's a huge difference in allocations! I'd say, about 3x to 5x overall, and instead of the images being 90% of it, it's now about 5% or so - big improvement. Also, much faster. Thanks so much!

There seems to be a bit of memory bumps due to retained objects (2x to 3x less than before though), but not 100% sure about that. Could just be because it's the first few requests and won't be there with later requests...we'll have to run this for a day or two to get a better feel for that part, but it's pretty safe to say the image side of it is fixed for us.

**Comment by earthlingworks** [comment] 2019-12-29 07:59
Ok, figured out where we're still seeing significant memory retained. It's from adding 3 true type fonts `pdf.fonts.add(...)`.

This shows up when those are added: https://share.getcloudapp.com/RBuXY4oZ

And we're already closing the IO stream object through the font wrapper, but I don't see a way to remove/delete those fonts from the document or clear up those resources.

**Comment by earthlingworks** [comment] 2019-12-29 08:02
Ah, almost forgot... these are the three fonts we're including (in case that helps): https://share.getcloudapp.com/7KuyPP4m

**Comment by gettalong** [comment] 2019-12-29 13:21
The `pdf.fonts` object has an internal cache to avoid loading the same file more than once. Since a reference to the font wrapper and therefore the font is held, it is not garbage collected. Setting the document variable to `nil` after it is not needed anymore, i.e. `pdf = nil` should allow Ruby to garbage collect the document object as well as all referenced objects.

Could you try this? 

An if you don't use those fonts (you mentioned you tried deleting them which would only make sense if they are not used by the PDF document), maybe you can avoid adding them in the first place?

**Comment by earthlingworks** [comment] 2019-12-29 21:58
We're actually using those font files, I was just thinking that we could delete them after the `.write(..)` to a new PDF file since we no longer will need them. 

Tried setting `pdf = nil` before (and still doing that) but didn't seem to make a difference. 

I think I narrowed down exactly what's happening. So it's a combination of fonts + the `.write`. Without doing a `.write` retained memory is much less. 

So I played around with the params in the `.write` and found that if we set `update_fields: false` almost all of the retained memory for the hexapdf gem goes away. It still seems to generate the new file as well. What's the downside of doing this with our actual files in production?

Here's the test code I was using:

    report = MemoryProfiler.report do

      open_file = open('/Users/ruben/hexa_test/test-contract.pdf')
      output_pdf = HexaPDF::Document.new(io: open_file)

      open_sans_wrapper = output_pdf.fonts.add('/var/www/bidsketch/docsketch/app/assets/fonts/OpenSans-Regular.ttf')
      cjk_fallback_wrapper = output_pdf.fonts.add('/var/www/bidsketch/docsketch/app/assets/fonts/DroidSans-Fallback.ttf')
      devanagari_fallback_wrapper = output_pdf.fonts.add('/var/www/bidsketch/docsketch/app/assets/fonts/Palanquin-Regular.ttf')

      output_pdf.pages.each_with_index do |page, index|
        overlay = page.canvas(:type => :overlay)
        # test image into StringIO
        overlay.image open('/Users/ruben/hexa_test/image1.png'), at: [200, 100], width: 100, height: 75
      end

      output_pdf.write('/Users/ruben/hexa_test/final.pdf', update_fields: false, validate: false, optimize: true)
      open_file.close unless open_file.closed?
      open_file = nil

      # cleanup
      open_sans_wrapper.wrapped_font.io.close
      cjk_fallback_wrapper.wrapped_font.io.close
      devanagari_fallback_wrapper.wrapped_font.io.close

      output_pdf = nil

    end

And the source PDF here: https://share.getcloudapp.com/7KuyPAAr

Note, it's definitely hugely improved since the 0.11.4 update - and much faster! This is just the last bit that still seems to be allocating and retaining a significant amount (especially for sidekiq).

**Comment by gettalong** [comment] 2019-12-29 23:46
The `update_fields` argument only updates some meta data in the info dictionary. Doing this is good behaviour but nothing more.

The reason why not calling `#write` has an influence on the objects is that the `hmtx` table of the TrueType fonts is only read when necessary. When writing the PDF file, the font needs to be embedded and during this the `hmtx` table is read. Same for the other font tables.

I ran your test code and switched `update_fields` from false to true but didn't see any difference in retained objects.

You don't need to explicitly close the IO streams if you are fine with them being auto-closed when the stream is not referenced anymore.

Still trying to figure out why the `HexaPDF::Document` instance is not garbage collected...

**Comment by earthlingworks** [comment] 2019-12-30 02:50
That's strange, I just tried changing the `update_fields` argument and it's making a big impact when I change it back and forth. 

Here's a screen recording of the retained memory having a large increase with `update_fields: true` and then going down when I change it to `update_fields: false`: https://share.getcloudapp.com/WnuEYqgp

Also, I thought maybe it was somehow related to my environment (I'm on a mac) so I changed that attribute on our staging server instance of the app, and it basically got rid of a big part of the retained memory we're seeing in sidekiq (seems to have a much bigger impact in sidekiq for some reason). 

One thing that's weird, is that in our app we're dynamically merging PDFs, and if I append pages (`.pages << output_pdf.import(page)`)  to a blank `HexaPDF::Document` document it blows up the memory, regardless of whether I have the `update_fields` argument set to true or false. 

I was able to duplicate this with the local test code. Might sound kind of confusing, so here's a video I recorded as I run through it (it has sound): https://share.getcloudapp.com/yAuLDKX5

Of course, even it wouldn't matter too much how many objects were allocated during running if we could get that garbage collected, but I haven't been able to do it in my staging environment, or even in my local dev environment (I even tried calling GC.start).

**Comment by gettalong** [comment] 2019-12-30 11:01
Thanks for the further information - I will see what I can find but it may take some days.

**Comment by earthlingworks** [comment] 2019-12-30 18:52
Sounds good; thanks!

**Comment by gettalong** [comment] 2019-12-30 23:29
So this is all a bit strange...

I tried working my way up from basically doing nothing to currently writing the PDF file with only fonts imported. Here is my test script:

~~~ ruby
# -*- frozen_string_literal: true -*-*

require 'memory_profiler'

report = MemoryProfiler.report(top: 5) do
  case ARGV[0]
  when '1'
    require 'hexapdf'
  when '2'
    require 'hexapdf'
    pdf = HexaPDF::Document.new
  when '3'
    require 'hexapdf'
    pdf = HexaPDF::Document.new
    pdf.write('final.pdf')
  when '4'
    require 'hexapdf'
    pdf = HexaPDF::Document.new
    pdf.fonts.add('/usr/share/fonts/truetype/freefont/FreeMono.ttf')
    pdf.fonts.add('/usr/share/fonts/truetype/freefont/FreeMonoBold.ttf')
    pdf.fonts.add('/usr/share/fonts/truetype/freefont/FreeMonoOblique.ttf')
    pdf.write('final.pdf')
  end

  pdf = nil
end
report.pretty_print(scale_bytes: true, retained_strings: 0, allocated_strings: 0)
~~~

Running tests 1, 2 or 3 always yields the same result, low allocations and few retained objects. However, when running 4 **sometimes** the retained objects are few and sometimes many:

~~~
retained objects by gem
-----------------------------------
      4974  rubygems
      1707  hexapdf-0.11.4
       290  x86_64-linux
        23  2.6.0
         6  time
~~~

vs.

~~~
retained objects by gem
-----------------------------------
     18535  hexapdf-0.11.4
      4975  rubygems
       291  x86_64-linux
        23  2.6.0
         6  time
~~~

Closing the IO streams of the fonts doesn't change the flipping result. Neither does changing `update_fields`.

I have also tried finding the object that holds a reference to the `HexaPDF::Document` instance using `ObjectSpace.dump_all` but was not really successful. There are some internal objects that have a reference to the document instance but this shouldn't matter.

This *could* mean that HexaPDF is not the root of the problem.

**Comment by earthlingworks** [comment] 2019-12-31 04:07
Very strange. Well, I had an idea on something I can check out but got sick and a bit out of it right now. Hopefully tomorrow I can check and report back. Thanks!

**Comment by gettalong** [comment] 2019-12-31 14:21
No worries! It's new year's eve :smile: - take your time and get better!

One more thing: I have tested the new PNG loader code with a bigger PNG (screenshot of my desktop) and it seems that performance is worse. This doesn't show up when using memory_profiler because of its overhead. In fact, the new code takes about 4s with that image while the old code about a minute. When not using memory_profiler, the new code takes 2s while the old one takes 1.5s. Will have to test a bit more...

**Comment by gettalong** [comment] 2020-01-05 22:21
So, I used benchmark-driver and the following benchmark spec:

~~~ yaml
prelude: |
  length = 1000
  str = Array.new(length) { 0.chr }.join.freeze
  count = 3
  alpha = 1
  f = "C#{count}x#{alpha}" * (length / (count + alpha))

benchmark:
  prev: |
    s = 0; r = "";
    while s < length
      r << str.byteslice(s, count)
      s += count + alpha
    end
  cur: |
    s = 0; r = "";
    while s < length
      count.times {|j| r << str.getbyte(s + j)}
      s += count + alpha
    end
  cur1: |
    s = 0; r = "";
    while s < length
      j = 0
      while j < count
        r << str.getbyte(s + j)
        j += 1
      end
      s += count + alpha
    end
  new: "r = str.unpack(f).pack('C*')"
~~~

This results in the following output:

~~~
Warming up --------------------------------------
                prev    27.431k i/s -     27.621k times in 1.006918s (36.45μs/i)
                 cur    11.089k i/s -     11.270k times in 1.016330s (90.18μs/i)
                cur1    12.724k i/s -     12.910k times in 1.014655s (78.59μs/i)
                 new    20.642k i/s -     22.462k times in 1.088163s (48.44μs/i)
Calculating -------------------------------------
                prev    26.371k i/s -     82.293k times in 3.120583s (37.92μs/i)
                 cur    10.860k i/s -     33.266k times in 3.063212s (92.08μs/i)
                cur1    12.877k i/s -     38.170k times in 2.964126s (77.66μs/i)
                 new    21.575k i/s -     61.926k times in 2.870204s (46.35μs/i)

Comparison:
                prev:     26371.0 i/s
                 new:     21575.5 i/s - 1.22x  slower
                cur1:     12877.3 i/s - 2.05x  slower
                 cur:     10859.8 i/s - 2.43x  slower
~~~

As you can see, the current version `cur` is the slowest variant. By removing the block invocation we can make it a bit faster but still two times slower than the original one.

The `new` version is only a bit slower but consumes more memory.

Therefore I'm inclined to revert back to the original version but I'm also thinking about moving this part to a C extension to make it faster. Would using a C extension work for you?

**Comment by earthlingworks** [comment] 2020-01-06 21:06
Hey! Thanks for the update. Sorry for the slower communication...just getting back into gear now. 

For the C extension, does that get automatically downloaded/installed when the gem is installed, or would that mean that there would be a separate install before the gem is installed?

**Comment by gettalong** [comment] 2020-01-07 00:01
The C extension would be in an optional gem so as to avoid making it a hard dependency and breaking the pure Ruby part of HexaPDF. You would need to install `hexapdf` and something like `hexapdf-cext` (not really thought about the name). However, requiring `hexapdf` would also look for the existence of the C extension and load it if it is available, to make the C extension seamless to use.

The C extension gem would then override CPU intensive methods with ones written in C.

As for your solution: Have a look at https://github.com/gettalong/hexapdf/blob/master/benchmark/raw_text/hexapdf.rb#L18 where I do something similar :smile: (although with out any permanent side effects).

**Comment by earthlingworks** [comment] 2020-01-07 02:37
Gotcha. Yeah, the extension should work well for us in that case 👍

And thanks for the suggestion; I'll give that a try!

**Comment by gettalong** [comment] 2020-01-07 09:53
Great, then I will look into creating that C extension!

**Comment by rainerborene** [comment] 2020-01-08 22:26
@gettalong you might want to take a look at [`helix`](https://github.com/tildeio/helix), [`faster_path`](https://github.com/danielpclark/faster_path), [`rutie`](https://github.com/danielpclark/rutie), and [`ruru`](https://github.com/d-unseductable/ruru).

**Comment by gettalong** [comment] 2020-01-08 22:47
@rainerborene Thanks for the llinks! I was aware of `ruru` but I would like to avoid adding another tool chain and language to the mix and go with what Ruby provides.

I have already a working version and will post an experimental gem to test soon.

**Comment by gettalong** [comment] 2020-01-11 10:42
@earthlingworks I have created an initial version of the C extension at https://github.com/gettalong/hexapdf-cext. Could you try that out and see if it helps?

**Comment by earthlingworks** [comment] 2020-01-14 02:13
This is great news! Thanks...sorry about the slow reply; I've been in the middle of a few projects, but I should be able to try it out in the next couple of days.

**Comment by earthlingworks** [comment] 2020-01-15 01:39
@gettalong Works great. I did get this warning installing the gem: https://share.getcloudapp.com/KouenX1k
 
Also, I'm still having trouble with memory retention related to fonts...I took your example code and used this larger CJK font (support for Chinese, Japanese, and Korean): https://share.getcloudapp.com/YEudDnY2

Super weird behavior that I'm consistently able to duplicate on the memory retention side, with a brand new document and this code:

     report = MemoryProfiler.report(top: 5) do
 
        pdf = HexaPDF::Document.new 
        pdf.fonts.add('/Users/ruben/hexa_test/NotoSansCJKtc-Regular.ttf')
        pdf.write('final.pdf', validate: false)
        
        pdf.pages.each do |page|
        end

      pdf = nil
    end
    report.pretty_print(scale_bytes: true, retained_strings: 0, allocated_strings: 0) 

I recorded this video showing what I get: https://share.getcloudapp.com/z8unlKl6

**Comment by gettalong** [comment] 2020-01-18 00:44
Hm... I don't get this warning. And it doesn't seem related to the gem itself since during the installation no code from the gem is executed. Have you tested installing the gem in a clean environment?

As for the memory retention related to fonts: I will modify the font code to lazily load some font tables which should avoid allocating memory for potentially not needed parts in the first place. However, I still don't know why the font object doesn't get garbage collected... :man_shrugging:

**Comment by gettalong** [comment] 2020-01-18 01:49
One more comment after watching your video: I can reproduce everything and *very* strange indeed.

The only thing that I can think of that could cause this behaviour is timing. Using the validation or removing the PDF pages loop may cause the garbage collector invocation to be invoked at the right moment so that the memory profiler doesn't see any retained memory anymore. However, when invoking `GC.start` right after `pdf = nil` it doesn't change a thing which should if my theory is right...

**Comment by gettalong** [comment] 2020-01-19 06:54
@earthlingworks I have pushed the latest changes, including the font related changes, to Github, can you try it out? The new code avoids parsing hmtx and cmap subtables when not necessary to save time and memory.

**Comment by earthlingworks** [comment] 2020-01-20 06:19
Great! I'll check it out tomorrow and will let you know.

**Comment by earthlingworks** [comment] 2020-01-21 00:21
Works much better! Though for the C extension and for these updates (both) I had to use `github:` and specificy the URL in the Gemfile since there doesn't seem to be release number.

**Comment by gettalong** [comment] 2020-01-21 10:27
Yes, there are no releases yet, this was just so that you can test the changes and see if the situation improves. The releases will come later this week!

**Comment by earthlingworks** [comment] 2020-01-21 19:54
Very good. Thanks for your help on all of this!

**Comment by gettalong** [comment] 2020-01-27 08:12
@earthlingworks The new releases of hexapdf and hexapdf-cext are out. Install them both and the C extension will automatically be used when it is available.

I will keep the issue open for now as a reminder to look into the memory retention thing.

**Comment by gettalong** [comment] 2021-01-10 08:12
@earthlingworks On twitter you said there is still a problem with memory? Is this still related to images?

You said in https://github.com/gettalong/hexapdf/issues/97#issuecomment-574455558 that you are still having problems with memory rentention when using fonts.

In this regard: Could you tell me a bit more about what you do? Especially, are you using HexaPDF in a long running process where you process different PDFs and often add the same (TrueType) font?

**Comment by earthlingworks** [comment] 2021-01-13 04:00
@gettalong Sorry for the late reply; I was on a trip with the family and catching up this week now that I'm back. 

There's definitely memory retention going on. Not sure if it's font usage exactly but based on what I had done, it seemed to point to that (at least partly). Short summary of how we're using HexaPDF: 

We're taking PDF documents and applying text and images on top of them. We basically let people fill out and sign documents through our UI, then we take the position and pages where they added this content and actually apply it to the real documents. Then we create an audit page that we attach to the end of the document. 

We do this work in Ruby code (it's a Rails app) and do it both by an action that gets called in a controller ("download pdf") and as a sidekiq job in other cases when we finalize the documents. Both ways of adding this data to PDFs use HexaPDF.

We always add Open Sans as the primary font, and then if language support is needed (like Chinese/Japanese/Korean) we add another font for that (which is rare).

**Comment by gettalong** [comment] 2021-01-13 14:07
@earthlingworks No problem, thanks for the details!

Just two more questions for details:

* You use HexaPDF in the Rails app and in Sidekiq. So this means both processes are long-lived and often create a new `HexaPDF::Document` instance?

* When adding the font, are you using `doc.fonts.add(font_path)` or `canvas.font(font_path, size: size)`?

**Comment by earthlingworks** [comment] 2021-01-14 00:30
@gettalong Not a problem!

Answers:

1. The process to create the documents I mentioned usually takes 1 to 3 seconds. It's pretty quick. 
2. Looks like we're mostly adding fonts this way: `doc.fonts.add(font_path)`

**Comment by gettalong** [comment] 2021-01-14 01:07
@earthlingworks Thanks for your answers!

With question 1 I meant whether the Rails and Sidekiq Ruby processes are long-running ones, i.e. if you process many documents with HexaPDF in the same Ruby instance.

As for 2: I have an idea that I will try out the next few days to see if I can reduce memory consumption when using TTF fonts.

**Comment by earthlingworks** [comment] 2021-01-14 02:33
@gettalong Ah, yes, it's a web app so they stay running and keep processing documents.

**Comment by earthlingworks** [comment] 2021-01-15 02:24
@gettalong So I just saw #103 and it seems like this fixes our memory issue as well. If we set `HexaPDF::Importer.instance_variable_set(:@map, nil)` retained memory is much better, regardless of whatever fonts are being imported. 

Problem is that we're running this as a web app (and also running as sidekiq processes), so being that `@map` is a class instance variable I'm guessing that if we did that in production, it would not be a good thing with multiple documents/requests being processed at the same time (not sequentially) all day long?

**Comment by earthlingworks** [comment] 2021-01-15 23:05
@gettalong not sure if this is helpful, but I found this interesting about weakref: https://share.getcloudapp.com/5zudzBOq

From this article (halfway down): https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby

**Comment by gettalong** [comment] 2021-01-15 23:56
@earthlingworks Thanks for the pointer! I actually read the article some time ago but it seems I didn't remember the gist when implementing the importer. I will see if something similar would help!

**Comment by gettalong** [comment] 2021-01-17 08:40
@earthlingworks Here is the latest change for long running processes using TrueType fonts: https://github.com/gettalong/hexapdf/commit/487db94518ce7592202dedb6c31d1f99a0dd0b7b - This will help without any code changes. Another change is up the pipeline to further enhance performance in such a case.

**Comment by gettalong** [comment] 2021-01-17 17:22
@earthlingworks With this change https://github.com/gettalong/hexapdf/commit/896a1515de23cd27bd958fd7c0fa6cd3f50c1242 you need to slightly adjust your code but can decrease object allocations and increase performance. Maybe this will help with memory retention, too. Will test this later in conjunction with #103.

**Comment by gettalong** [comment] 2021-01-17 22:55
So I looked again at your comment https://github.com/gettalong/hexapdf/issues/97#issuecomment-574455558 to see if I could figure the problem. However, I was not able to reproduce the strange behaviour. The result I got was always low retained memory, on different Ruby versions and with/without your changes.

Once I added some text in that TrueType font to a page, more memory was retained. It seems to me that the HexaPDF::Document instance never gets garbage collected but the problem only gets visible if something it references uses a lot of memory.

**Comment by gettalong** [comment] 2021-01-18 17:48
@earthlingworks I have a potential fix for the import retention problem - see https://github.com/gettalong/hexapdf/commit/a13a3e903c5fea3cd96ec9c329f5213cbfe27afd. Could you try the devel branch to see if this helps?

It was tested with this script:

~~~ ruby
require 'hexapdf'

big_pdf = HexaPDF::Document.open(File.open(ARGV[0]))

big_pdf.pages.each_with_index do |page, index|
  target_pdf = HexaPDF::Document.new
  target_pdf.import(page)
end

var = HexaPDF::Importer.instance_variable_get(:@map) || {}
p var: var.size
~~~

When running without the mentioned commit, it would print out `{:var => 52}` (because the supplied document has that many pages), with the commit it prints `{:var => 5}`.

**Comment by earthlingworks** [comment] 2021-01-18 20:38
@gettalong Just tried out `a13a3e9` in my local test environment and it looks great! Big improvements on memory. Can't deploy that to production until it comes out as a normal release but yeah, I think this is going to take care of the majority of our issues on the memory side. Excited to try it on production :) 

Going to try out the updates related to fonts a bit later today and will get back to you on those. Thanks!

**Comment by earthlingworks** [comment] 2021-01-19 01:02
@gettalong For the font commits, definitely good for lower allocations though the retained memory seems to be more about the importer, so between all these I think we'll be in great shape.

**Comment by gettalong** [comment] 2021-01-21 00:27
@earthlingworks Thanks for the feedback! I will close the issue now since I think everything is resolved here.

**Closed by gettalong** 2021-01-21 00:27 UTC

**Comment by gettalong** [comment] 2021-01-21 00:33
@earthlingworks New release is out!

**Comment by earthlingworks** [comment] 2021-01-21 01:06
@gettalong Excellent - thank you!
