### ISSUE TITLE
Invalid number of color components, 1|3|4 expected, 0 given

### ISSUE THREAD

**Issue by ksocha** [gettalong/hexapdf#132] opened 2021-03-22 12:30 UTC
Hi!

I have the above issue when filling in text fields in existing PDF document. I use the latest version of hexapdf.

Unfortunately, I'm not allowed to attach the document itself. But here is result of `hexapdf inspect file r`:
[inspect.txt](https://github.com/gettalong/hexapdf/files/6182090/inspect.txt)

Also, here's the stacktrace, if it's of any help:
```
"hexapdf-0.14.4/lib/hexapdf/content/color_space.rb:140:in `for_components'"
"hexapdf-0.14.4/lib/hexapdf/content/color_space.rb:128:in `prenormalized_device_color'"
"hexapdf-0.14.4/lib/hexapdf/type/annotations/widget.rb:115:in `background_color'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/appearance_generator.rb:307:in `apply_background_and_border'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/appearance_generator.rb:256:in `create_text_appearances'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/text_field.rb:220:in `block in create_appearances'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/field.rb:254:in `each_widget'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/text_field.rb:217:in `create_appearances'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/text_field.rb:226:in `update_widgets'"
"hexapdf-0.14.4/lib/hexapdf/type/acro_form/text_field.rb:170:in `field_value='"
```

The result I have is a document with values being invisible. After user focuses on one of the fields, value from that field becomes visible until unfocused.

Is there anything that can be done to somehow force field appearance to be recreated?

**Comment by gettalong** [comment] 2021-03-22 13:15
Thanks for providing the inspect output!

It seems that this part is causing the issue:

~~~
            /MK {obj 65} <<
              /BC []
              /BG []
            >>
~~~

After looking at the spec the error is caused by a bug in HexaPDF where for the background color the empty array is not treated as transparent. The code for the border color works fine.

I will fix this for the next release.

**Comment by ksocha** [comment] 2021-03-22 13:16
@gettalong  Thank you!

**Comment by gettalong** [comment] 2021-03-26 18:43
This is fixed and will be in the next release.

**Closed by gettalong** 2021-03-26 18:43 UTC
Labels: bug

**Comment by ksocha** [comment] 2021-03-30 10:37
Thanks! May I ask when do you plan to release next version?

**Comment by gettalong** [comment] 2021-03-30 17:20
There is another feature lined up which will get into that release and I expect a new release in the next 14 days.
