### ISSUE TITLE
How to flatten PDF fields that have javascript widgets associated?

### ISSUE THREAD

**Issue by mdonagh** [gettalong/hexapdf#172] opened 2022-01-22 21:23 UTC
[example.pdf](https://github.com/gettalong/hexapdf/files/7919299/example.pdf)
See example PDF here - this has the fields populated, I cannot figure out how to get them to flatten.

I've been able to get the fields populated with the below:
```
 field = obj.document.acro_form.field_by_name(obj[:T])
 field.field_value = string_to_write
```

However, when I flatten the PDF fields with the below, they are all empty.

```
document.pages.each do |page|
  page.flatten_annotations
end
```

Also, when I flatten the fields this way rather than our legacy method, `strings = PDF::Inspector::Text.analyze(pdf).strings` cannot read the strings. Why is that?

Legacy method below:
```
        style = HexaPDF::Layout::Style.new(font: canvas.font, fill_color: color, stroke_color: color, align: :left, valign: :center)
        fragment = HexaPDF::Layout::TextFragment.create(str, style)
        layouter = HexaPDF::Layout::TextLayouter.new(style)
        layouter.fit([fragment], w, h).draw(canvas, x1, y2)
```

Your help would be greatly appreciated here @gettalong Thomas, thanks in advance

**Comment by gettalong** [comment] 2022-01-22 23:26
I have looked at it but can't reproduce the problem (I ran into a bug while trying various things that will be fixed with the next release, though).

I tried the following script:

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.open('/tmp/example.pdf')
doc.acro_form.flatten(create_appearances: false)
doc.write('/tmp/flattened.pdf')
~~~

The resulting file shows the form fields when inspecting visually: 
![image](https://user-images.githubusercontent.com/4104/150658587-3fd5e946-f64f-4de0-8589-334445b3f0b5.png)

I also tried modifying a field inserting this line before flattening:
~~~ ruby
doc.acro_form.field_by_name("ADDRESS 1").field_value = "Some Address Here 1"
~~~

This also works: 
![image](https://user-images.githubusercontent.com/4104/150658666-b61fd057-cc7b-4338-9309-d03abf51b113.png)


Could you provide a short example script where this problem appears? Thank you!

**Comment by gettalong** [comment] 2022-03-03 16:05
@mdonagh I just tried this again to make sure it still doesn't work for me with the latest code and, alas, I still can't reproduce the problem. Could you provide a sample script?

**Comment by gettalong** [comment] 2022-03-26 22:32
@mdonagh Since you haven't responded and I can't reproduce the problem, I will close the issue. If this is still a problem, please let me know and I will re-open the issue.

**Closed by gettalong** 2022-03-26 22:32 UTC
