### ISSUE TITLE
TypeError: class or module required

### ISSUE THREAD

**Issue by PetrKaleta** [gettalong/hexapdf#46] opened 2018-09-03 16:56 UTC
Raises when calling document.write

```
TypeError: class or module required
1
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/dictionary_fields.rb" line 220 in kind_of?
2
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/dictionary_fields.rb" line 220 in convert?
3
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/dictionary_fields.rb" line 168 in convert?
4
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/dictionary.rb" line 159 in []
5
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/type/trailer.rb" line 75 in info
6
File "/app/vendor/bundle/ruby/2.5.0/gems/hexapdf-0.7.0/lib/hexapdf/document.rb" line 600 in write
```

**Comment by gettalong** [comment] 2018-09-03 18:57
Can you add some more details? E.g. Ruby version used? An example to reproduce the problem?

**Comment by PetrKaleta** [comment] 2018-09-03 20:17
`ruby 2.5.1p57` just opened PDF, modified some hyperlinks target inside and write it with validation turned off.

**Comment by gettalong** [comment] 2018-09-04 03:50
Okay, the code looks fine. Does it happen for all PDFs or just for some? If it is the latter, can you provide such a problematic PDF so that I can inspect it?

**Comment by gettalong** [comment] 2018-09-07 19:09
@PetrKaleta I looked through the stack trace and the corresponding code but without a reproducible example it is quite hard to determine the problem. What might also help is a list of libraries you are using.

**Comment by gettalong** [comment] 2018-10-26 08:50
@PetrKaleta I will close this issue since I didn't hear back from you and I can't reproduce the problem. Feel free to add the needed information so that I can debug the problem and I will re-open the issue - thanks!

**Comment by BriKutauskas** [comment] 2019-05-02 15:10
I am also experiencing this problem with the same ruby version with this code block:

 `def merge_class_tests(test, target)
    tests.joins(:exam_attachment).distinct.each do |test|
      report_path = "#{Dir.tmpdir}/#{test.exam.filename}"
      File.open(report_path, 'wb') do |file|
        file.write(test.exam.download)
      end
      pdf = HexaPDF::Document.open(report_path)
      pdf.pages.each { |page| target.pages << target.import(page) }
    ensure
      FileUtils.rm_f(report_path) if report_path
    end
  end`

The strange part is that it only happens on occasion and if I experience the error and then execute the code again I do not experience this error again.

**Comment by gettalong** [comment] 2019-05-03 17:26
@BriKutauskas Does it happen only for certain source PDF files? If so, could you provide such a PDF and possibly sample code?

Do you use the latest version?

**Comment by BriKutauskas** [comment] 2019-05-06 15:07
@gettalong I am using the latest version of HexaPDF (0.9.0). I have also attached an example of a pdf that returned that error at some point during the build but I was able to successfully generate it on the next build.

[example_missing_module.pdf](https://github.com/gettalong/hexapdf/files/3148520/example_missing_module.pdf)

The pdfs are originally generated using Prawn. Let me know if there are any other helpful details I can provide.

**Comment by gettalong** [comment] 2019-05-09 16:37
@BriKutauskas Thanks for the PDF - I will see if I can reproduce the problem. Is the sample PDF as `target` in your sample code or one of the test files?

**Comment by BriKutauskas** [comment] 2019-05-14 17:27
Great, thank you. The sample pdf is target in the code above.

**Comment by gettalong** [comment] 2019-06-13 14:35
@BriKutauskas I'm sorry but I was not able to reproduce the problem yet, even with your target PDF and some Prawn PDFs I got... If you have a reproducible code sample and the respective PDFs, it would be really helpful.

**Comment by gettalong** [comment] 2019-07-01 18:36
@PetrKaleta There were some changes in the DictionaryFields implementation after you raised this issue. Does this error still occur with the latest version of HexaPDF for you?

@BriKutauskas Do you have a stack trace like in the initial issue description that you could share?

**Comment by gettalong** [comment] 2019-07-23 21:22
@PetrKaleta @BriKutauskas There may be some race condition involved that leads to this error. The error can only appear if `#kind_of?` gets a non-module/class as argument. This can only happen if the type of a field is defined by a symbol in which case HexaPDF normally should map it to the correct class at runtime. However, if multiple threads are accessing the same document simultaneously, this  might be a problem and may lead to this error.

So are you accessing a single document in multiple threads?

**Comment by tfwright** [comment] 2019-08-23 00:25
I'm seeing this as well and I'm pretty sure it's not a race condition (it's happening consistently with certain pdfs while others work), although obviously I'm not sure. Unfortunately I can't share the specific pdfs because they contain sensitive information.

This is the stack trace: https://gist.github.com/tfwright/dbb2c98f696e0d195251257ff4f51fe1

**Comment by gettalong** [comment] 2019-08-23 08:24
Thanks for providing the stack trace!

**Comment by gettalong** [comment] 2019-08-23 08:56
@tfwright @PetrKaleta @BriKutauskas Could you try the latest repository version? Thanks to @tfwright's stack trace I found a mistyped field type name.

**Comment by tfwright** [comment] 2019-08-23 13:17
Sorry, I don't seem to be able to install the gem from the master branch or the latest commit ref. Tried `gem 'hexapdf', github: 'gettalong/hexapdf', branch: 'master'` and `gem 'hexapdf', github: 'gettalong/hexapdf', branch: '8f40d10c8678542701638c38a9234245f44727cf'`

```
Fetching git://github.com/gettalong/hexapdf.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'hexapdf' in git://github.com/gettalong/hexapdf.git (at 8f40d10@8f40d10).
The source does not contain any versions of 'hexapdf'
```

**Comment by gettalong** [comment] 2019-08-23 20:04
You need to download the latest repository version from Github and put it in your Ruby lib path. Or run `rake dev:gem; gem install pkg/hexapdf-*.gem`.

Direct usage of HexaPDF via Github is not supported.

**Comment by gettalong** [comment] 2019-08-31 20:56
@tfwright @PetrKaleta @BriKutauskas I have tried to reproduce the given stack trace with the following program:

~~~ ruby
require 'hexapdf'
require 'stringio'

doc = HexaPDF::Document.new
popup = doc.add(Type: :Annot, Subtype: :Popup, Rect: [1,2,3,4])
annot = doc.add(Type: :Annot, Subtype: :Text, Popup: popup, Rect: [1,2,3,4])
doc.write(StringIO.new)
~~~

With 0.9.3 I get the following stack trace:

~~~
Traceback (most recent call last):
        30: from bugs/issue46.rb:6:in `<main>'
        29: from lib/hexapdf/document.rb:619:in `write'
        28: from lib/hexapdf/document.rb:575:in `validate'
        27: from lib/hexapdf/document.rb:403:in `each'
        26: from lib/hexapdf/document.rb:403:in `reverse_each'
        25: from lib/hexapdf/document.rb:404:in `block in each'
        24: from lib/hexapdf/revision.rb:185:in `each'
        23: from lib/hexapdf/utils/object_hash.rb:120:in `each'
        22: from lib/hexapdf/utils/object_hash.rb:120:in `each'
        21: from lib/hexapdf/utils/object_hash.rb:120:in `block in each'
        20: from lib/hexapdf/revision.rb:185:in `block in each'
        19: from lib/hexapdf/document.rb:406:in `block (2 levels) in each'
        18: from lib/hexapdf/document.rb:577:in `block in validate'
        17: from lib/hexapdf/object.rb:270:in `validate'
        16: from lib/hexapdf/object.rb:270:in `catch'
        15: from lib/hexapdf/object.rb:271:in `block in validate'
        14: from lib/hexapdf/type/annotations/text.rb:65:in `perform_validation'
        13: from lib/hexapdf/type/annotations/markup_annotation.rb:63:in `perform_validation'
        12: from lib/hexapdf/dictionary.rb:264:in `perform_validation'
        11: from lib/hexapdf/dictionary.rb:255:in `each_set_key_or_required_field'
        10: from lib/hexapdf/dictionary.rb:255:in `each_key'
         9: from lib/hexapdf/dictionary.rb:255:in `block in each_set_key_or_required_field'
         8: from lib/hexapdf/dictionary.rb:265:in `block in perform_validation'
         7: from lib/hexapdf/dictionary.rb:166:in `[]'
         6: from lib/hexapdf/dictionary_fields.rb:166:in `convert'
         5: from lib/hexapdf/dictionary_fields.rb:166:in `each'
         4: from lib/hexapdf/dictionary_fields.rb:167:in `block in convert'
         3: from lib/hexapdf/dictionary_fields.rb:122:in `type'
         2: from lib/hexapdf/dictionary_fields.rb:122:in `map!'
         1: from lib/hexapdf/dictionary_fields.rb:124:in `block in type'
lib/hexapdf/configuration.rb:127:in `constantize': Error getting constant for configuration option 'object.type_map' and keys 'Annotation' (HexaPDF::Error)
~~~

With the repository version the error disappears as expected.

However, the above stack trace is **not** the same as the one from @tfwright:

~~~ diff
-lib/hexapdf/dictionary_fields.rb:194:in `convert'
+lib/hexapdf/dictionary_fields.rb:122:in `type'
lib/hexapdf/dictionary_fields.rb:167:in `block in convert'
~~~

The above program jumps from the block into the `type` method whereas for @tfwright it jumps to convert, producing an error there because the `type` method provides erroneous information.

@tfwright Can you provide the contents of `field` and `value` at `lib/hexapdf/dictionary.rb:166:in `[]'` for a failed run?

Another idea: Maybe some other library messes with classes/modules outside its namespace and caues the error in HexaPDF? Have you tried reducing your code to a minimal version (ideally only with HexaPDF as dependency) that still throws the error?

**Comment by gettalong** [comment] 2019-09-01 21:23
@tfwright @PetrKaleta @BriKutauskas Another possible cause: Are you catching errors somewhere and then recovering? Could you check if you run into the `HexaPDF::Error` above and recover it?

Because if you catch that error you won't run into it the second time the `#type` method is called due to caching.

**Comment by gettalong** [comment] 2019-09-16 08:01
@tfwright @PetrKaleta @BriKutauskas I will close this issue since as far as I can determine the bug is fixed. If this is not the case, please report again and I will re-open the issue.

**Closed** 2019-09-16 08:02 UTC

**Comment by enthusiasmus** [comment] 2019-10-02 15:06
Hi gettalong!

We are receiving the same error. We are using Hexapdf to add an overlay to an existing pdf. The pdf was generated by Indesign. The write text and images to the pdf. But we couldn't reliably reproduce it. 

Stacktrace:
```
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary_fields.rb:194 in kind_of?
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary_fields.rb:194 in convert
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary_fields.rb:167 in block in convert
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary_fields.rb:166 in each
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary_fields.rb:166 in convert
/gems/hexapdf-0.9.3/lib/hexapdf/dictionary.rb:166 in []
/gems/hexapdf-0.9.3/lib/hexapdf/type/trailer.rb:78 in info
/gems/hexapdf-0.9.3/lib/hexapdf/document.rb:615 in write
app/lib/pdf/voucher.rb:70 in write
    private def write
      document.write(pdf, optimize: true)
```
Version: 0.9.3

Any ideas?
Best regards,
Lukas

**Comment by gettalong** [comment] 2019-10-02 20:11
@enthusiasmus I will release version 0.10.0 later today - please try that version because as far as I can tell the bug should be fixed.

**Comment by enthusiasmus** [comment] 2019-10-13 19:21
@gettalong works! thanks for your quick response!
