### ISSUE TITLE
FrozenError: can't modify frozen String: "" in serializer.

### ISSUE THREAD

**Issue by JStadtmullerExlabs** [gettalong/hexapdf#192] opened 2022-09-16 15:39 UTC
During the run code:

```
      result = StringIO.new
      document.original_file.open do |original|
        HexaPDF::Document.new(io: original).write(result, optimize: true)
      end
```

I receive erro: `FrozenError: can't modify frozen String: ""` on `gems/ruby-2.7.6/gems/hexapdf-0.24.2/lib/hexapdf/serializer.rb:280:in `gsub!'` 

The fun fact is that the error appears only when method `write` is called with the flag `optimize: true`.

**Comment by gettalong** [comment] 2022-09-16 16:39
Could you provide the `original_file` in question where this happens? This would make finding the error easier. What would also help: Is the original file encrypted?

The place where the error happens ensures that the string is modifiable *except* in the case for string encryption. However, an empty frozen string should not lead to an error when using `.gsub!`:

~~~
irb(main):001:0> RUBY_VERSION
=> "3.1.0"
irb(main):002:0> x = ''.freeze
=> ""
irb(main):003:0> ''.gsub!(/[()\\\r]/, {'(' => 'x'})
=> nil
~~~

So I don't really know what is going on in your case.

However, I will modify the serialization of strings to ensure that an encrypted string is `dup`ped to avoid a similar error for encrypted documents (I'm not quite sure why this error hasn't already happened...).

**Comment by JStadtmullerExlabs** [comment] 2022-09-20 12:17
Thanks for the quick answer! Unfortunately, I can't provide an original_file because of legal reasons. But it was not encrypted, as far as I know.  When I fought about problem I think that this code describe the problem better:
```
irb(main):011:0> RUBY_VERSION
=> "2.7.6"
irb(main):012:0> x = ''.freeze
=> ""
irb(main):013:0> ''.gsub!(/[()\\\r]/, {'(' => 'x'})
=> nil
irb(main):014:0> y = x
=> ""
irb(main):015:0> y.gsub!(/[()\\\r]/, {'(' => 'x'})
Traceback (most recent call last):
        2: from (irb):15
        1: from (irb):15:in `gsub!'
FrozenError (can't modify frozen String: "")
```

**Comment by gettalong** [comment] 2022-09-20 13:46
Oops, you are perfectly right :upside_down_face: . I naturally wanted to `x.gsub!` :man_facepalming: and that raises the error.

You can check whether it is encrypted by running `hexapdf info file.pdf`:

~~~
File name:          out.pdf
File size:          23432 bytes
Producer:           HexaPDF version 0.24.2
ModDate:            2022-09-20 15:42:08 +0200
Encrypted:          yes (version: 4, key length: 128bits)
  String algorithm: aes
  Stream algorithm: aes
  EFF algorithm:    aes
  Permissions:
Pages:              1
Version:            1.5
~~~

If it has the line with 'Encrypted:', it is encrypted.

If you can't provide the file (I could also sign an NDA if needed, contact me at info@gettalong.at if that would work for you), maybe you can provide the full stack trace? And the output of `hexapdf inspect file.pdf r`? The latter will show the structure and meta information of the file but nothing that is visible on the pages which should be fine in most cases.

**Comment by JStadtmullerExlabs** [comment] 2022-09-21 08:45
Thank you very much for the option to the personal contact with you, I really appreciate that proposition. But unfortunately, this file contains very sensitive data and it will be almost impossible to get permission to send it to you. But I will try to provide all the meta information that I can. 

`hexapdf info file.pdf`
```
File name:          ../corrupted.pdf
File size:          299489 bytes
Title:              Document
Producer:           e2 Rendering Engine 5.5M0p0300
Encrypted:          yes (version: 1, key length: 40bits)
  String algorithm: arc4
  Stream algorithm: arc4
  EFF algorithm:    arc4
  Permissions:      print, fill_in_forms, extract_content, assemble_document, high_quality_print
Pages:              5
Version:            1.4
```
So my mistake, that file is encrypted ;)

**Comment by gettalong** [comment] 2022-09-21 09:39
That's great news because what I thought might be the problem is nearly surely the problem. Since I have already fixed that, there should be no error anymore when the new version of HexaPDF comes out (end of September/start of October).

I will close this issue now. Please let me know if there is still a problem once you tested the new version.

**Closed by gettalong** 2022-09-21 09:39 UTC
