### ISSUE TITLE
`Type1 encoding has no codepoint for ...` when editing existing pdf

### ISSUE THREAD

**Issue by ksocha** [gettalong/hexapdf#113] opened 2020-08-14 13:07 UTC
Hi,

Thanks for the latest update! I wanted to use acro_form code to update some fields in existing PDF documents I have.
However, setting text fields do not work in my case. When I try to do sth like following: `field.field_value = 'test'` I get `Type1 encoding has no codepoint for t` error.

What can be a possible cause? Should I do something more to make it work? Unfortunately docs are not saying anything about modifying existing pdfs.

**Comment by gettalong** [comment] 2020-08-14 14:03
Thanks for the feedback! This might be a problem with HexaPDF or the PDF in question. Since support for AcroForm is new, not many "in the wild" tests have been done and there are certainly cases out there where HexaPDF won't do the correct thing (the PDF spec is sometimes rather vague...).

Can you provide the PDF in question? Or if not, can you run `hexapdf inspect INPUT.PDF r` on the file in question and provide the output? This will help me narrow done the fault.

## Detailed explanation

The PDF viewer (or the library filling out the form) sets the field value which is just a dictionary value. If done only this way, there are no visual changes. PDF viewers have no choice but to generate a visual appearance (because how else should the user see the entered value). Libraries, however, can stop at assigning a value and set a flag so that the generation of the visual appearance is done by the viewer.

This mostly works but some viewers don't respect/understand that flag and won't show the set value. Therefore it is always good that the library generates the visual appearance, too.

HexaPDF does this, ie. generation of the visual appearance. It boils down to `canvas.text(field.field_value)` (*much* simplified). For this, HexaPDF needs to know which glyph (visual appearance of a character) corresponds to each Unicode character. This information is stored in the encoding of the font.

And here comes the twist: Which font has to be used? This is set by the application creating the form and stored in the main interactive form object. However, the font has to be specified in a way so that the application processing the PDF can retrieve the glyph for a certain character. Because of this "complication" and the file size implications most forms use one of the standard PDF fonts like Helvetica or Times-Roman because those need to be available to every PDF processor.

When HexaPDF encounters a text field with a font it cannot use, it falls back to a pre-defined font set via a configuration option. However, in your case it seems that a font is specified that HexaPDF can potentially use but where the encoding seems off.

I have to update the topic page on interactive forms with regards to this, i.e. how fonts are handled for variable text fields.

**Comment by ksocha** [comment] 2020-08-14 17:00
@gettalong  Thank you for very detail explanation.

Unfortunately I'm not allowed to attach the pdf itself but below is the result of the inspect command:
[inspect_result.txt](https://github.com/gettalong/hexapdf/files/5075916/inspect_result.txt)

**Comment by gettalong** [comment] 2020-08-14 18:00
@ksocha Thanks and no problem! After a quick look at the output I think I can reproduce the problem. Just one more question: Does this problem appear with all text fields or just some? If the latter, could you provide the name of one of the fields? Thanks!

**Comment by ksocha** [comment] 2020-08-14 18:19
I’ve tried it with few fields and had the issue with all of them. I think the same will happen for others as well.

**Comment by gettalong** [comment] 2020-08-14 19:04
Thanks! Will get back to you when I have determined the cause.

**Comment by gettalong** [comment] 2020-08-14 20:20
@ksocha I think I have found the problem and it is a bug in how difference encodings are handled with type 1 fonts. Will test some more and provide the fix on the devel branch for you to test.

**Comment by ksocha** [comment] 2020-08-14 20:25
Thank you for extremely fast response. I’ll test when possible and let you know ASAP.

**Comment by gettalong** [comment] 2020-08-14 21:46
@ksocha I have pushed a preliminary fix to the devel branch. I stumbled upon a possible other problem in the process but wanted to give you something to test asap so I can see if this fixes your problem.

Please let me know if it does, then I will release the bug fix.

**Comment by ksocha** [comment] 2020-08-15 18:56
@gettalong I just checked it out and it seems to work fine. Good job!

**Comment by gettalong** [comment] 2020-08-15 20:31
@ksocha Thank you! I will still need to check the other problem and then release a bug fix version.

**Comment by gettalong** [comment] 2020-08-16 06:33
Fixed with 0.12.1 release!

**Closed by gettalong** 2020-08-16 06:33 UTC
Labels: bug
