### ISSUE TITLE
Editable PDF problem

### ISSUE THREAD

**Issue by kryna** [gettalong/hexapdf#74] opened 2019-07-05 13:28 UTC
I'm completing editable PDF form on back-end side using something like:
```ruby
reference` = ::HexaPDF::Reference.new(number)
doc.object(reference)[:V] = value
```
and some of editable PDF works fine but in some cases input seems to to be empty but after it's clicked values are shown. 

For example, the one generated by `Adobe InDesign CC 13.1 (Macintosh)` works fine but another generated by `Microsoft Excel` has this disappearing issue.

Do you know any solutions to that problem or maybe you can point me in the right direction where to look for solution or what needs to be changed.

**Comment by gettalong** [comment] 2019-07-05 19:02
I guess your `number` is a valid object number of the PDF file in question? If so, you can use it directly with `HexaPDF::Document#object`, i.e. `doc.object(number)`. However, getting a reference object first and then resolving it also works.

Without the PDFs in question it is hard to tell you what may be wrong. So if it is possible for you, providing one that works and one that doesn't along with all needed information to reproduce the problem (object number, ...) would greatly help.

What you can do is look at all the other values set on the form field by Adobe InDesign and check whether those are also set by Excel. The problem might also be caused by missing/corrupted appearance streams. Have you tried with different PDF applications?

**Comment by kryna** [comment] 2019-07-23 10:52
Sorry for the long response time. I can only send you failing PDF (I will send it to email account from your profile - t_leitner@gmx.at). Can we start with that?

**Comment by gettalong** [comment] 2019-07-23 15:42
Thanks for the PDF - as I mentioned I would also need the information for reproducing the problem - can you provide a link to the code that produces the problem?

**Comment by kryna** [comment] 2019-07-29 09:56
I think the following code would be enough.

```ruby
    def call(document, params)
      @document = document
      @params = params

      open_document
      add_data
      save_document
    end

    private

    attr_accessor :document, :doc, :params

    def open_document
      @doc = HexaPDF::Document.open(document.file.path)
    end

    def add_data
      params[:pdf_data].each do |key, value|
        reference = ::HexaPDF::Reference.new(key.to_i)
        doc.object(reference)[:V] = value
      end
    end

    def save_document
      doc.write(document.file.path)
      document.save
    end
```

**Comment by gettalong** [comment] 2019-07-29 13:02
@kryna Thanks but to reproduce the problem, I would also need the value of the +params+ hash.

**Comment by kryna** [comment] 2019-07-29 14:20
```ruby
{"pdf_data"=>
  {"70R"=>"",
   "69R"=>"",
   "68R"=>"",
   "67R"=>"",
   "66R"=>"",
   "65R"=>"",
   "64R"=>"",
   "63R"=>"",
   "62R"=>"",
   "61R"=>"",
   "60R"=>"",
   "59R"=>"",
   "58R"=>"",
   "57R"=>"",
   "56R"=>"122323B London",
   "54R"=>"Main",
   "53R"=>"Doe",
   "52R"=>"John",
   "51R"=>"Name of company",
   "55R"=>"1A/23"}}
```

**Comment by gettalong** [comment] 2019-08-01 11:07
@kryna Thanks for the PDF, code and data. After looking at everything and reading the PDF specification, I found the problem.

The fields of the PDF contain an `/AP` entry which, if present, is displayed by the PDF viewer. So if you additionally sets the `/V` value it doesn't really matter for the viewing application. By deleting the `/AP` key, you tell the viewer that no appearance stream for the field has been pre-generated and that it should generate one from the `/V` value and other entries in the field dictionary.

So if you set a new value for a text field, delete the `/AP` key and everything should work.

**Closed by gettalong** 2019-08-01 11:07 UTC
Labels: question

**Comment by kryna** [comment] 2019-08-14 14:10
Thank you, this solution works 👍

**Comment by kryna** [comment] 2019-08-20 10:43
Hi @gettalong, there're still problems with `date` fields. If you replace empty string for `59R` key with any text and run the code, inputs will be empty but this time even clicking it doesn't show the value.

**Comment by gettalong** [comment] 2019-08-20 21:26
Hm... If I try this with object id=59 and open the resulting PDF in okular, the filled in text appears correctly.

However, if you look at the AcroForm object id=49, you will find that it doesn't contain a field with object id=59 but one with id=6. The page itself contains object id=59 in its /Annots array but not one with id=6.

Object id=6 is the date form field and it has two widget annotations as children (the two places where the date can appear). For example, if you use Adobe Reader to open the PDF, you will find that changing one date field also changes the other. 

If you set `/V` on object id=6, id=59 and id=60 and delete `/AP` from id=59 and id=60, the resulting PDF looks fine in okular/evince but still not in Adobe Reader. It seems that it needs an `/AP` key if the widget annotation is a child of form field, as is the case here, because deleting the `/AP`(generated by filling out the document with a reader) will result in Adobe Reader not showing anything.

**Comment by gettalong** [comment] 2019-10-19 07:38
@kryna: @smiller and I found a solution for the disappearing problem. It seems Acrobat only generates appearance streams if instructed to do so -  see https://github.com/gettalong/hexapdf/issues/86#issuecomment-544110920.
